all:
  vars:
    ansible_port: 22
  hosts:
    lvm:
      ansible_host: IP
      ansible_user: root
      ansible_ssh_private_key_file: /home/murphycooper/key.pem
    source:
      ansible_host: IP
      ansible_user: aprisma
      ansible_password: aprisma